# Generated by Django 4.1.1 on 2022-09-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_before_db',
            name='before_file',
            field=models.FileField(upload_to='C:\\Users\\lee seung min\\Desktop\\prohome\\professor-s-office\\media\\before'),
        ),
    ]
